# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 1.1.{build}


#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: EFdoXCV4TKpY1I6HVQgnW0SXO/d8GB8OqFqu3q15rrxU/ISP2NykYmTxYXwoePuJ

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1